import { scaleFont } from "@/constants/ScaleFont";
import { Dimensions, Platform, StyleSheet } from "react-native";
const ScreenWidth = Dimensions.get('window').width;
const ScreenHeight = Dimensions.get('window').height;
export const styles = StyleSheet.create({
    background: {
      flex: 1,
      backgroundColor: '#fff',
    },
    headerSection: {
      backgroundColor: '#5F8A8B',
      height: ScreenHeight * 0.15,
      borderBottomLeftRadius: 100,
      borderBottomRightRadius: 100,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 20,
    },
    signUpText: {
      fontSize: scaleFont(28),
      fontWeight: 'bold',
      color: '#FFFFFF',
      fontFamily: 'Poppins-Light',
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageContainer: {
      marginTop: Platform.OS === 'android' ? ScreenHeight*0.05 : 0,
      alignItems: 'center',
      marginBottom: 10,
    },
    illustrationImage: {
      width: ScreenWidth * 0.5,
      height: ScreenHeight * 0.2,
    },
    cardContainer: {
      backgroundColor: '#FFFFFF',
      width: ScreenWidth ,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingVertical: 24,
      paddingHorizontal: 20,
    },
    formContainer: {
      width: '100%',
    },
    inputWrapper: {
      marginBottom: 20,
      paddingHorizontal: 12,

    },
    inputLabel: {
      fontSize: scaleFont(15),
      color: '#374151',
      fontFamily: 'Poppins-Light',
      fontWeight: 'bold',
      marginBottom: Platform.OS === 'ios' ? 15 : 0,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#d1d5d8',
    },
    inputIcon: {
      marginRight: 0,
      marginBottom: Platform.OS === 'ios' ? 15 : 0,
    },
    input: {
      flex: 1,
      fontSize: scaleFont(15),
      color: '#1F2937',
      fontFamily: 'Poppins-Light',
      paddingHorizontal: 15,
      marginBottom: Platform.OS === 'ios' ? 15 : 0,
    },
    inputError: {
      borderColor: '#EF4444',
      borderWidth: 1,
    },
    errorText: {
      color: '#EF4444',
      fontSize: scaleFont(14),
      marginTop: 2,
      fontFamily: 'Poppins-Light',
    },
    createAccountButton: {
      backgroundColor: '#008541',
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: 14,
      // marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    createAccountButtonText: {
      color: '#FFFFFF',
      fontSize: scaleFont(16),
      fontWeight: 'bold',
      fontFamily: 'Poppins-Light',
    },
    orDividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 20,
    },
    orDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: '#d1d5d8',
    },
    orText: {
      marginHorizontal: 16,
      fontSize: scaleFont(14),
      color: '#6B7280',
      fontWeight: '500',
      fontFamily: 'Poppins-Light',
    },
    scanQRButton: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 25,
      borderWidth: 1,
      borderColor: '#009333',
      // marginTop: 10,
    },
    scanQRButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    scanQRButtonText: {
      color: '#008541',
      fontSize: scaleFont(15),
      fontWeight: '600',
      marginLeft: 8,
      fontFamily: 'Poppins-Light',
    },
    loginTextContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 8,
    },
    loginText: {
      color: '#6B7280',
      fontSize: scaleFont(14),
      fontFamily: 'Poppins-Light',
    },
    loginLink: {
      color: '#008541',
      fontSize: scaleFont(14),
      fontWeight: 'bold',
      fontFamily: 'Poppins-Light',
    },
    container: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    text: {
      marginBottom: 5,
      fontWeight: 'medium',
      color: 'black',
      alignSelf: 'flex-start',
      paddingHorizontal: 30,
      fontSize: scaleFont(17),
      fontFamily: 'Poppins-Light',
    },
    header: {
      marginBottom: 20,
      fontWeight: 'semibold',
      color: 'black',
      alignSelf: 'center',
      fontSize: scaleFont(22),
      fontFamily: 'Poppins-Light',
    },
    button: {
      marginTop: 20,
      marginBottom: 10,
      alignSelf: 'center',
    },
    error: {
      color: 'red',
      alignSelf: 'flex-start',
      fontFamily: 'Poppins-Light',
      fontSize: scaleFont(17),
      paddingHorizontal: 30,
    },
    cameraContainer: {
      flex: 1,
      justifyContent: 'center',
      backgroundColor: '#008541',
      
    },
    cameraPreview: {
      width: ScreenWidth,
      height: ScreenHeight,
      marginTop: scaleFont(30), // Adjusted height to leave space for the header
    },
    modalView: {
      margin: 20,
      marginTop: '80%',
      backgroundColor: 'transparent',
      borderRadius: 20,
      padding: 35,
      alignItems: 'center',
      shadowColor: '#fff',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    cameraHeader: {
      position: 'relative',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 10,
      backgroundColor: '#008541',
      width: ScreenWidth,
      zIndex: 1,
      marginTop: ScreenHeight*0.05,
    },
    barcodeText: {
      textAlign: 'justify',
      fontSize: scaleFont(18),
      marginLeft: 4,
      fontWeight: 'bold',
      color: '#fff',
    },
    camerabordercontainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 20, // Added margin for better visibility
      height: ScreenHeight,
    },
    scannerFrame: {
      position: 'absolute',
      top: '15%',
      left: '10%',
      width: '80%',
      height: '40%',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: '#008541',
      borderRadius: 20,
    },
    uploadButtonWrapper: {
      position: 'absolute',
      bottom: scaleFont(220),
      width: '100%',
      alignItems: 'center',
      zIndex: 2,
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 4,
    },
    uploadButtonText: {
      color: '#111827',
      fontSize: scaleFont(15),
      fontFamily: 'Poppins-Light',
      textAlignVertical: 'center',
      includeFontPadding: false,
      textAlign: 'center',
      fontWeight: '900',
    },
  });